# Generated by Django 6.0.2 on 2026-04-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
            ],
            options={
                'db_table': 'barcodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('asin', models.CharField(max_length=50)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bundle_qty', models.IntegerField(blank=True, db_column='bundleQty', null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('image_url', models.TextField(blank=True, db_column='imageUrl', null=True)),
                ('is_archived', models.BooleanField(db_column='isArchived', default=False)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_column='createdAt')),
                ('updated_at', models.DateTimeField(db_column='updatedAt')),
            ],
            options={
                'db_table': 'product_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SoStockedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_id', models.BigIntegerField(db_index=True, unique=True)),
                ('asin', models.CharField(db_index=True, max_length=20)),
                ('area_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.CharField(db_index=True, max_length=30)),
                ('order_number', models.CharField(blank=True, default='', max_length=100)),
                ('param_diff', models.SmallIntegerField(default=0)),
                ('real_diff', models.SmallIntegerField(default=0)),
                ('old_qty', models.IntegerField(null=True)),
                ('new_qty', models.IntegerField(null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('vendor_name', models.CharField(blank=True, default='', max_length=200)),
                ('product_name', models.CharField(blank=True, default='', max_length=500)),
                ('order_shipment_id', models.CharField(blank=True, default='', max_length=50)),
                ('type_id', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'asin'], name='logs_sostoc_created_72c4d5_idx'), models.Index(fields=['type_id', '-created_at'], name='logs_sostoc_type_id_7944c4_idx')],
            },
        ),
    ]
