# Generated by Django 6.0.2 on 2026-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sostockedlog',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
